use_frameworks!

platform :ios, '15.0'

target 'LibExample_Example' do
  pod 'LibExample', :path => '../'
end

target 'LibExample_Tests' do
  inherit! :search_paths
  pod 'LibExample', :path => '../'
  pod 'Quick', '~> 2.2.0'
#  pod 'Nimble', '~> 10.0.0'
#  pod 'FBSnapshotTestCase' , '~> 2.1.4'
#  pod 'Nimble-Snapshots' , '~> 9.4.0'
end

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'

      # --- 兼容Xcode15 ---
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      #-------------------
    end
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
    end
  end
end
